//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnalyticsEntities : DbContext
    {
        public AnalyticsEntities()
            : base("name=AnalyticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalibrationStandard> CalibrationStandards { get; set; }
        public virtual DbSet<Info> Infoes { get; set; }
        public virtual DbSet<List> Lists { get; set; }
        public virtual DbSet<QC> QCs { get; set; }
        public virtual DbSet<SampleAnion> SampleAnions { get; set; }
        public virtual DbSet<SampleCation> SampleCations { get; set; }
        public virtual DbSet<SampleIron> SampleIrons { get; set; }
        public virtual DbSet<STDAnion> STDAnions { get; set; }
        public virtual DbSet<STDCation> STDCations { get; set; }
        public virtual DbSet<STDIron> STDIrons { get; set; }
        public virtual DbSet<Submission> Submissions { get; set; }
        public virtual DbSet<Sequence> Sequences { get; set; }
    }
}
