//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public Info()
        {
            this.Lists = new HashSet<List>();
            this.Submissions = new HashSet<Submission>();
        }
    
        public int InfoID { get; set; }
        public string FileName { get; set; }
        public string Submitter { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public string Plate_Name { get; set; }
        public string Carbon_Source { get; set; }
        public string t_dot_C_Source { get; set; }
        public string Strains { get; set; }
        public string Other_Analytes { get; set; }
        public string Project { get; set; }
        public string Group { get; set; }
        public string Special_Instructions { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string SpreadsheetType { get; set; }
        public Nullable<double> Feed { get; set; }
        public string SampleType { get; set; }
        public string KeyAnalytes { get; set; }
        public string ConcGL { get; set; }
        public string SubmissionName { get; set; }
    
        public virtual ICollection<List> Lists { get; set; }
        public virtual ICollection<Submission> Submissions { get; set; }
    }
}
