//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int ListID { get; set; }
        public Nullable<int> InfoID { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public Nullable<System.DateTime> SampleDate { get; set; }
        public Nullable<int> Date { get; set; }
        public string Strain { get; set; }
        public string Tank { get; set; }
        public Nullable<decimal> DecimalTime { get; set; }
        public string Stage { get; set; }
        public string ListName { get; set; }
        public Nullable<decimal> DilutionFactor { get; set; }
        public string ListTab { get; set; }
    
        public virtual Info Info { get; set; }
    }
}
