//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutlineItem
    {
        public int Id { get; set; }
        public int RunId { get; set; }
        public int TankId { get; set; }
        public int OutlineTopicId { get; set; }
        public int OutlineDescriptionId { get; set; }
        public int PersonId { get; set; }
        public string Value { get; set; }
        public bool Checked { get; set; }
        public int ValuesState { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual Run Run { get; set; }
    }
}
