//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutlineDescription
    {
        public int Id { get; set; }
        public int OutlineTopicId { get; set; }
        public string Name { get; set; }
        public string OutlineTopicName { get; set; }
        public int ValuesState { get; set; }
        public Nullable<bool> Checked { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual OutlineTopic OutlineTopic { get; set; }
    }
}
