//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DistinguishedName { get; set; }
        public string SAMAccountName { get; set; }
        public string EmailAddress { get; set; }
        public string Alarm { get; set; }
        public int Pin { get; set; }
        public string GivenName { get; set; }
        public string MiddleName { get; set; }
        public string SurName { get; set; }
        public string VoiceTelephoneNumber { get; set; }
        public string LoginName { get; set; }
        public int Status { get; set; }
        public string ImageFileURI { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
