//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PilotPlantEntities : DbContext
    {
        public PilotPlantEntities()
            : base("name=PilotPlantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GrowthPhase> GrowthPhases { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<MachineReadingDescription> MachineReadingDescriptions { get; set; }
        public virtual DbSet<OutlineDescription> OutlineDescriptions { get; set; }
        public virtual DbSet<OutlineItem> OutlineItems { get; set; }
        public virtual DbSet<OutlineTopic> OutlineTopics { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Reading> Readings { get; set; }
        public virtual DbSet<ReadingDescription> ReadingDescriptions { get; set; }
        public virtual DbSet<ReadingSession> ReadingSessions { get; set; }
        public virtual DbSet<RotatedReading> RotatedReadings { get; set; }
        public virtual DbSet<Run> Runs { get; set; }
        public virtual DbSet<RunHistory> RunHistories { get; set; }
        public virtual DbSet<SamplePlan> SamplePlans { get; set; }
        public virtual DbSet<SamplePlanDetail> SamplePlanDetails { get; set; }
        public virtual DbSet<Tank> Tanks { get; set; }
        public virtual DbSet<RunStatus> RunStatus { get; set; }
    }
}
