//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QC
    {
        public int Id { get; set; }
        public string Submission_Filename { get; set; }
        public string Team { get; set; }
        public string Submitter { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Received { get; set; }
        public Nullable<int> Sample__ { get; set; }
        public string Sample_state { get; set; }
        public Nullable<int> GC_4 { get; set; }
        public Nullable<int> LC_ { get; set; }
        public Nullable<int> IC_An { get; set; }
        public Nullable<int> IC_Ca { get; set; }
        public Nullable<int> IC_Me { get; set; }
        public Nullable<int> KF_ { get; set; }
        public Nullable<int> Tiamo { get; set; }
        public Nullable<int> MP { get; set; }
        public Nullable<int> ASH { get; set; }
        public string Prepped_by { get; set; }
        public string Processed_by { get; set; }
        public Nullable<System.DateTime> Reported { get; set; }
        public string Posted_by { get; set; }
        public string Archive_Location { get; set; }
        public string Comments { get; set; }
    }
}
