//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Run
    {
        public Run()
        {
            this.OutlineItems = new HashSet<OutlineItem>();
            this.SamplePlans = new HashSet<SamplePlan>();
            this.SamplePlanDetails = new HashSet<SamplePlanDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Rundate { get; set; }
        public Nullable<System.DateTime> RunStart { get; set; }
        public Nullable<System.DateTime> InductionStart { get; set; }
        public int MachineId { get; set; }
        public int ProductId { get; set; }
        public int RunStatusId { get; set; }
        public int GrowthPhaseId { get; set; }
        public string Comments { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual ICollection<OutlineItem> OutlineItems { get; set; }
        public virtual ICollection<SamplePlan> SamplePlans { get; set; }
        public virtual ICollection<SamplePlanDetail> SamplePlanDetails { get; set; }
    }
}
