//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunHistory
    {
        public int Id { get; set; }
        public int RunId { get; set; }
        public int TankId { get; set; }
        public int ReadingDescriptionId { get; set; }
        public string ValueArray { get; set; }
    }
}
