//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Process.Models
{
    using System;
    using System.Collections.Generic;

    public partial class SampleAnion
    {
        public int Id { get; set; }
        [Display(Name = "Sample Date")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> SampleDate { get; set; }

        [Display(Name = "Sample Serial No")]
        public string SampleSerialNo { get; set; }

        public string Ident { get; set; }
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Dilution { get; set; }

        [Display(Name = "F Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> F__Area { get; set; }

        [Display(Name = "Acet Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Acet__Area { get; set; }

        [Display(Name = "Cl Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Cl__Area { get; set; }

        [Display(Name = "Br Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Br__Area { get; set; }

        [Display(Name = "NO3 Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> NO3_Area { get; set; }

        [Display(Name = "Po4 Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Po4_Area { get; set; }

        [Display(Name = "So4 Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> So4_Area { get; set; }
        
        [Display(Name = "F PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> F_PPM { get; set; }
        
        [Display(Name = "Acet PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Acet_PPM { get; set; }
        
        [Display(Name = "Cl PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Cl_PPM { get; set; }
        
        [Display(Name = "Br PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Br_PPM { get; set; }
        
        [Display(Name = "No3 PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> No3_PPM { get; set; }
        
        [Display(Name = "Po4 PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Po4_PPM { get; set; }
        
        [Display(Name = "So4 PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> So4_PPM { get; set; }
        public string SpreadsheetLink { get; set; }
    }
}
