//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamplePlan
    {
        public SamplePlan()
        {
            this.SamplePlanDetails = new HashSet<SamplePlanDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RunId { get; set; }
        public string WordFileUri { get; set; }
        public string ExcelFileUri { get; set; }
    
        public virtual Run Run { get; set; }
        public virtual ICollection<SamplePlanDetail> SamplePlanDetails { get; set; }
    }
}
