//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamplePlanDetail
    {
        public int Id { get; set; }
        public Nullable<int> SamplePlanId { get; set; }
        public int RunId { get; set; }
        public string Name { get; set; }
        public string DateAndTime { get; set; }
        public bool IsPrepared { get; set; }
        public Nullable<System.DateTime> DatePrepared { get; set; }
        public string PreparedBy { get; set; }
        public bool IsWeighed { get; set; }
        public Nullable<System.DateTime> DateWeighed { get; set; }
        public string WeighedBy { get; set; }
        public bool IsSubmitted { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public string SubmittedBy { get; set; }
    
        public virtual Run Run { get; set; }
        public virtual SamplePlan SamplePlan { get; set; }
    }
}
