//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sequence
    {
        public int ID { get; set; }
        public Nullable<double> Serial_No { get; set; }
        public string Submission_Filename { get; set; }
        public string Team { get; set; }
        public string SubmittedBy { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Received { get; set; }
        public string Method { get; set; }
        public Nullable<double> NumberOfSamples { get; set; }
        public string PreppedBy { get; set; }
        public string Instrument { get; set; }
        public string ProcessedBy { get; set; }
        public Nullable<System.DateTime> Reported { get; set; }
        public string SentBy { get; set; }
        public Nullable<double> TAT { get; set; }
        public string Comments { get; set; }
        public string Archive_Location { get; set; }
        public Nullable<int> InfoID { get; set; }
        public string Pathname { get; set; }
        public string SpreadsheetVersion { get; set; }
        public string Column1 { get; set; }
        public string Column2 { get; set; }
    }
}
