//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using Process.Models;

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STDIron
    {
        public int Id { get; set; }
        public int CalibrationStandardId { get; set; }

        [Display(Name = "Sample Date")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> CalibrationDate { get; set; }

        public string Ident { get; set; }
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Dilution { get; set; }

        [Display(Name = "Fe III Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Fe__III__Area { get; set; }

        [Display(Name = "Cu Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Cu_Area { get; set; }

        [Display(Name = "Ni Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Ni_Area { get; set; }

        [Display(Name = "Zn Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Zn_Area { get; set; }

        [Display(Name = "Co Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Co_Area { get; set; }

        [Display(Name = "Mn Area")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Mn_Area { get; set; }

        [Display(Name = "Fe III PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Fe__III__PPM { get; set; }

        [Display(Name = "Cu PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Cu_PPM { get; set; }

        [Display(Name = "Ni PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Ni_PPM { get; set; }

        [Display(Name = "Zn PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Zn_PPM { get; set; }

        [Display(Name = "Co PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Co_PPM { get; set; }

        [Display(Name = "Mn PPM")]
        [DisplayFormat(DataFormatString = "{0:F3}")]
        public Nullable<decimal> Mn_PPM { get; set; }

    
        public virtual CalibrationStandard CalibrationStandard { get; set; }
    }
}
