//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int SubmissionID { get; set; }
        public Nullable<int> InfoID { get; set; }
        public Nullable<int> Number_Of_Samples { get; set; }
        public Nullable<int> Sequence_No { get; set; }
        public string SOP { get; set; }
        public string Instrument { get; set; }
        public string TabName { get; set; }
    
        public virtual Info Info { get; set; }
    }
}
